FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

WORKDIR /src/src/Pusula.Training.HealthCare.DbMigrator
RUN dotnet publish "Pusula.Training.HealthCare.DbMigrator.csproj" -c Release -o /app/blazor

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS migrator
WORKDIR /app

COPY --from=build /app/migrator .

ENTRYPOINT ["dotnet", "Pusula.Training.HealthCare.DbMigrator.dll"]
